version: "3.9"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped

    ports:
      - "8200-8220:8200-8220"   # generic range (requested)
      - "8200:8080"             # Jenkins UI -> http://localhost:8200
      - "8210:50000"            # inbound agents (JNLP)

    environment:
      - JAVA_OPTS=
      - JENKINS_HOME=/var/jenkins_home

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw  # talk to host Docker

    networks:
      - default
      - shared

    user: "0:0"   # entrypoint will drop to 'jenkins'

volumes:
  jenkins_home:

networks:
  shared:
    external: true
    name: shared_net
