services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped

    # Exposed ports:
    # - 8200 -> Jenkins UI (internal 8080)
    # - 8242 -> JNLP agents (internal 50000)
    # - 8215 -> extra port you requested (1:1 mapping)
    ports:
      - "8200:8080"
      - "8242:50000"
      - "8215:8215"

    environment:
      - JAVA_OPTS=
      - JENKINS_HOME=/var/jenkins_home

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw

    # Connected to three networks (default, shared, edge)
    networks:
      - default
      - shared
      - edge

    # Running as root to ensure Docker socket access (as per your current setup)
    user: "0:0"

  nginx:
    image: nginx:stable-alpine
    container_name: jenkins-nginx
    restart: unless-stopped

    # Publish HTTP and HTTPS (HTTP is redirected to HTTPS in nginx/jenkins.conf)
    ports:
      - "80:80"
      - "443:443"

    volumes:
      # Nginx vhost for Jenkins reverse proxy (includes HTTPS config)
      - ./nginx/jenkins.conf:/etc/nginx/conf.d/jenkins.conf:ro
      # TLS certs: place fullchain.pem and privkey.pem here
      - ./nginx/certs:/etc/nginx/certs:ro

    depends_on:
      - jenkins

    # Reverse proxy sits on edge + shared networks
    networks:
      - edge
      - sh
