services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped

    ports:
      - "8200:8080"      # UI
      - "8242:50000"     # JNLP agents
      - "8215:8215"      # extra port που ζήτησες

    environment:
      - JAVA_OPTS=
      - JENKINS_HOME=/var/jenkins_home

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw

    networks:
      - default
      - shared
      - edge

    user: "0:0"

  nginx:
    image: nginx:stable-alpine
    container_name: jenkins-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/jenkins.conf:/etc/nginx/conf.d/jenkins.conf:ro
      # - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - jenkins
    networks:
      - edge
      - shared

volumes:
  jenkins_home:

networks:
  shared:
    external: true
    name: shared_net
  edge:
    driver: bridge
