services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped

    # Publish ports:
    # - Keep your requested range (shifted to avoid 8200 collision)
    # - UI on 8200 -> internal 8080
    # - Agents on 8242 -> internal 50000
    ports:
      - "8201-8220:8201-8220"
      - "8200:8080"
      - "8242:50000"

    environment:
      - JAVA_OPTS=
      - JENKINS_HOME=/var/jenkins_home

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw

    networks:
      - default
      - shared
      - edge

    user: "0:0"

  nginx:
    image: nginx:stable-alpine
    container_name: jenkins-nginx
    restart: unless-stopped
    # Αν θες να τον χρησιμοποιείς, εκθέτεις 80 (και 443 αργότερα)
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/jenkins.conf:/etc/nginx/conf.d/jenkins.conf:ro
      # - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - jenkins
    networks:
      - edge
      - shared

volumes:
  jenkins_home:

networks:
  shared:
    external: true
    name: shared_net
  edge:
    driver: bridge
